name: punch_star_arena
description: Battle royale espacial 2D con Flutter, Flame y WebSockets.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/sprites/
    - assets/images/tilesets/
    - assets/images/effects/
