name: asistente_dibujo_ia
description: "Demo Flutter de function calling con Ollama para dibujar figuras en un canvas."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
